/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZaproszenieRouteImport } from './routes/zaproszenie'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as BootstrapRouteImport } from './routes/bootstrap'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthenticatedZdarzenieRouteImport } from './routes/_authenticated/zdarzenie'
import { Route as AuthenticatedUrlopyRouteImport } from './routes/_authenticated/urlopy'
import { Route as AuthenticatedStatystykiRouteImport } from './routes/_authenticated/statystyki'
import { Route as AuthenticatedRaportyRouteImport } from './routes/_authenticated/raporty'
import { Route as AuthenticatedPulpitRouteImport } from './routes/_authenticated/pulpit'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedOgloszeniaRouteImport } from './routes/_authenticated/ogloszenia'
import { Route as AuthenticatedGrafikRouteImport } from './routes/_authenticated/grafik'
import { Route as AuthenticatedDyspozycyjnoscRouteImport } from './routes/_authenticated/dyspozycyjnosc'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AuthenticatedAdminUzytkownicyRouteImport } from './routes/_authenticated/admin/uzytkownicy'
import { Route as AuthenticatedAdminUrlopyRouteImport } from './routes/_authenticated/admin/urlopy'
import { Route as AuthenticatedAdminSluzbyRouteImport } from './routes/_authenticated/admin/sluzby'
import { Route as AuthenticatedAdminRaportyRouteImport } from './routes/_authenticated/admin/raporty'
import { Route as AuthenticatedAdminPojazdyRouteImport } from './routes/_authenticated/admin/pojazdy'
import { Route as AuthenticatedAdminOgloszeniaRouteImport } from './routes/_authenticated/admin/ogloszenia'
import { Route as AuthenticatedAdminNieprzydzieloneRouteImport } from './routes/_authenticated/admin/nieprzydzielone'
import { Route as AuthenticatedAdminMonitorRouteImport } from './routes/_authenticated/admin/monitor'
import { Route as AuthenticatedAdminMapaRouteImport } from './routes/_authenticated/admin/mapa'
import { Route as AuthenticatedAdminKomunikatyRouteImport } from './routes/_authenticated/admin/komunikaty'
import { Route as AuthenticatedAdminKierowcyRouteImport } from './routes/_authenticated/admin/kierowcy'
import { Route as AuthenticatedAdminIncydentyRouteImport } from './routes/_authenticated/admin/incydenty'
import { Route as AuthenticatedAdminDziennikRouteImport } from './routes/_authenticated/admin/dziennik'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicRobloxPositionRouteImport } from './routes/api/public/roblox/position'
import { Route as ApiPublicRobloxPisRouteImport } from './routes/api/public/roblox/pis'
import { Route as ApiPublicRobloxIncidentRouteImport } from './routes/api/public/roblox/incident'
import { Route as ApiPublicRobloxDutyRouteImport } from './routes/api/public/roblox/duty'
import { Route as ApiPublicRobloxDriverRouteImport } from './routes/api/public/roblox/driver'
import { Route as ApiPublicRobloxAckRouteImport } from './routes/api/public/roblox/ack'
import { Route as AuthenticatedSluzbaDutyIdZdarzenieRouteImport } from './routes/_authenticated/sluzba.$dutyId.zdarzenie'
import { Route as AuthenticatedSluzbaDutyIdRozkladRouteImport } from './routes/_authenticated/sluzba.$dutyId.rozklad'
import { Route as AuthenticatedSluzbaDutyIdRaportRouteImport } from './routes/_authenticated/sluzba.$dutyId.raport'
import { Route as AuthenticatedSluzbaDutyIdMapaRouteImport } from './routes/_authenticated/sluzba.$dutyId.mapa'

const ZaproszenieRoute = ZaproszenieRouteImport.update({
  id: '/zaproszenie',
  path: '/zaproszenie',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const BootstrapRoute = BootstrapRouteImport.update({
  id: '/bootstrap',
  path: '/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedZdarzenieRoute = AuthenticatedZdarzenieRouteImport.update({
  id: '/zdarzenie',
  path: '/zdarzenie',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUrlopyRoute = AuthenticatedUrlopyRouteImport.update({
  id: '/urlopy',
  path: '/urlopy',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStatystykiRoute = AuthenticatedStatystykiRouteImport.update({
  id: '/statystyki',
  path: '/statystyki',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRaportyRoute = AuthenticatedRaportyRouteImport.update({
  id: '/raporty',
  path: '/raporty',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPulpitRoute = AuthenticatedPulpitRouteImport.update({
  id: '/pulpit',
  path: '/pulpit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOgloszeniaRoute = AuthenticatedOgloszeniaRouteImport.update({
  id: '/ogloszenia',
  path: '/ogloszenia',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGrafikRoute = AuthenticatedGrafikRouteImport.update({
  id: '/grafik',
  path: '/grafik',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDyspozycyjnoscRoute =
  AuthenticatedDyspozycyjnoscRouteImport.update({
    id: '/dyspozycyjnosc',
    path: '/dyspozycyjnosc',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminUzytkownicyRoute =
  AuthenticatedAdminUzytkownicyRouteImport.update({
    id: '/uzytkownicy',
    path: '/uzytkownicy',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUrlopyRoute =
  AuthenticatedAdminUrlopyRouteImport.update({
    id: '/urlopy',
    path: '/urlopy',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSluzbyRoute =
  AuthenticatedAdminSluzbyRouteImport.update({
    id: '/sluzby',
    path: '/sluzby',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRaportyRoute =
  AuthenticatedAdminRaportyRouteImport.update({
    id: '/raporty',
    path: '/raporty',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPojazdyRoute =
  AuthenticatedAdminPojazdyRouteImport.update({
    id: '/pojazdy',
    path: '/pojazdy',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOgloszeniaRoute =
  AuthenticatedAdminOgloszeniaRouteImport.update({
    id: '/ogloszenia',
    path: '/ogloszenia',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNieprzydzieloneRoute =
  AuthenticatedAdminNieprzydzieloneRouteImport.update({
    id: '/nieprzydzielone',
    path: '/nieprzydzielone',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMonitorRoute =
  AuthenticatedAdminMonitorRouteImport.update({
    id: '/monitor',
    path: '/monitor',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMapaRoute = AuthenticatedAdminMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminKomunikatyRoute =
  AuthenticatedAdminKomunikatyRouteImport.update({
    id: '/komunikaty',
    path: '/komunikaty',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminKierowcyRoute =
  AuthenticatedAdminKierowcyRouteImport.update({
    id: '/kierowcy',
    path: '/kierowcy',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIncydentyRoute =
  AuthenticatedAdminIncydentyRouteImport.update({
    id: '/incydenty',
    path: '/incydenty',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDziennikRoute =
  AuthenticatedAdminDziennikRouteImport.update({
    id: '/dziennik',
    path: '/dziennik',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRobloxPositionRoute = ApiPublicRobloxPositionRouteImport.update({
  id: '/api/public/roblox/position',
  path: '/api/public/roblox/position',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRobloxPisRoute = ApiPublicRobloxPisRouteImport.update({
  id: '/api/public/roblox/pis',
  path: '/api/public/roblox/pis',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRobloxIncidentRoute = ApiPublicRobloxIncidentRouteImport.update({
  id: '/api/public/roblox/incident',
  path: '/api/public/roblox/incident',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRobloxDutyRoute = ApiPublicRobloxDutyRouteImport.update({
  id: '/api/public/roblox/duty',
  path: '/api/public/roblox/duty',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRobloxDriverRoute = ApiPublicRobloxDriverRouteImport.update({
  id: '/api/public/roblox/driver',
  path: '/api/public/roblox/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRobloxAckRoute = ApiPublicRobloxAckRouteImport.update({
  id: '/api/public/roblox/ack',
  path: '/api/public/roblox/ack',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSluzbaDutyIdZdarzenieRoute =
  AuthenticatedSluzbaDutyIdZdarzenieRouteImport.update({
    id: '/sluzba/$dutyId/zdarzenie',
    path: '/sluzba/$dutyId/zdarzenie',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSluzbaDutyIdRozkladRoute =
  AuthenticatedSluzbaDutyIdRozkladRouteImport.update({
    id: '/sluzba/$dutyId/rozklad',
    path: '/sluzba/$dutyId/rozklad',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSluzbaDutyIdRaportRoute =
  AuthenticatedSluzbaDutyIdRaportRouteImport.update({
    id: '/sluzba/$dutyId/raport',
    path: '/sluzba/$dutyId/raport',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSluzbaDutyIdMapaRoute =
  AuthenticatedSluzbaDutyIdMapaRouteImport.update({
    id: '/sluzba/$dutyId/mapa',
    path: '/sluzba/$dutyId/mapa',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bootstrap': typeof BootstrapRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/zaproszenie': typeof ZaproszenieRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dyspozycyjnosc': typeof AuthenticatedDyspozycyjnoscRoute
  '/grafik': typeof AuthenticatedGrafikRoute
  '/ogloszenia': typeof AuthenticatedOgloszeniaRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/pulpit': typeof AuthenticatedPulpitRoute
  '/raporty': typeof AuthenticatedRaportyRoute
  '/statystyki': typeof AuthenticatedStatystykiRoute
  '/urlopy': typeof AuthenticatedUrlopyRoute
  '/zdarzenie': typeof AuthenticatedZdarzenieRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/dziennik': typeof AuthenticatedAdminDziennikRoute
  '/admin/incydenty': typeof AuthenticatedAdminIncydentyRoute
  '/admin/kierowcy': typeof AuthenticatedAdminKierowcyRoute
  '/admin/komunikaty': typeof AuthenticatedAdminKomunikatyRoute
  '/admin/mapa': typeof AuthenticatedAdminMapaRoute
  '/admin/monitor': typeof AuthenticatedAdminMonitorRoute
  '/admin/nieprzydzielone': typeof AuthenticatedAdminNieprzydzieloneRoute
  '/admin/ogloszenia': typeof AuthenticatedAdminOgloszeniaRoute
  '/admin/pojazdy': typeof AuthenticatedAdminPojazdyRoute
  '/admin/raporty': typeof AuthenticatedAdminRaportyRoute
  '/admin/sluzby': typeof AuthenticatedAdminSluzbyRoute
  '/admin/urlopy': typeof AuthenticatedAdminUrlopyRoute
  '/admin/uzytkownicy': typeof AuthenticatedAdminUzytkownicyRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/sluzba/$dutyId/mapa': typeof AuthenticatedSluzbaDutyIdMapaRoute
  '/sluzba/$dutyId/raport': typeof AuthenticatedSluzbaDutyIdRaportRoute
  '/sluzba/$dutyId/rozklad': typeof AuthenticatedSluzbaDutyIdRozkladRoute
  '/sluzba/$dutyId/zdarzenie': typeof AuthenticatedSluzbaDutyIdZdarzenieRoute
  '/api/public/roblox/ack': typeof ApiPublicRobloxAckRoute
  '/api/public/roblox/driver': typeof ApiPublicRobloxDriverRoute
  '/api/public/roblox/duty': typeof ApiPublicRobloxDutyRoute
  '/api/public/roblox/incident': typeof ApiPublicRobloxIncidentRoute
  '/api/public/roblox/pis': typeof ApiPublicRobloxPisRoute
  '/api/public/roblox/position': typeof ApiPublicRobloxPositionRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bootstrap': typeof BootstrapRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/zaproszenie': typeof ZaproszenieRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dyspozycyjnosc': typeof AuthenticatedDyspozycyjnoscRoute
  '/grafik': typeof AuthenticatedGrafikRoute
  '/ogloszenia': typeof AuthenticatedOgloszeniaRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/pulpit': typeof AuthenticatedPulpitRoute
  '/raporty': typeof AuthenticatedRaportyRoute
  '/statystyki': typeof AuthenticatedStatystykiRoute
  '/urlopy': typeof AuthenticatedUrlopyRoute
  '/zdarzenie': typeof AuthenticatedZdarzenieRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/dziennik': typeof AuthenticatedAdminDziennikRoute
  '/admin/incydenty': typeof AuthenticatedAdminIncydentyRoute
  '/admin/kierowcy': typeof AuthenticatedAdminKierowcyRoute
  '/admin/komunikaty': typeof AuthenticatedAdminKomunikatyRoute
  '/admin/mapa': typeof AuthenticatedAdminMapaRoute
  '/admin/monitor': typeof AuthenticatedAdminMonitorRoute
  '/admin/nieprzydzielone': typeof AuthenticatedAdminNieprzydzieloneRoute
  '/admin/ogloszenia': typeof AuthenticatedAdminOgloszeniaRoute
  '/admin/pojazdy': typeof AuthenticatedAdminPojazdyRoute
  '/admin/raporty': typeof AuthenticatedAdminRaportyRoute
  '/admin/sluzby': typeof AuthenticatedAdminSluzbyRoute
  '/admin/urlopy': typeof AuthenticatedAdminUrlopyRoute
  '/admin/uzytkownicy': typeof AuthenticatedAdminUzytkownicyRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/sluzba/$dutyId/mapa': typeof AuthenticatedSluzbaDutyIdMapaRoute
  '/sluzba/$dutyId/raport': typeof AuthenticatedSluzbaDutyIdRaportRoute
  '/sluzba/$dutyId/rozklad': typeof AuthenticatedSluzbaDutyIdRozkladRoute
  '/sluzba/$dutyId/zdarzenie': typeof AuthenticatedSluzbaDutyIdZdarzenieRoute
  '/api/public/roblox/ack': typeof ApiPublicRobloxAckRoute
  '/api/public/roblox/driver': typeof ApiPublicRobloxDriverRoute
  '/api/public/roblox/duty': typeof ApiPublicRobloxDutyRoute
  '/api/public/roblox/incident': typeof ApiPublicRobloxIncidentRoute
  '/api/public/roblox/pis': typeof ApiPublicRobloxPisRoute
  '/api/public/roblox/position': typeof ApiPublicRobloxPositionRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/bootstrap': typeof BootstrapRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/zaproszenie': typeof ZaproszenieRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dyspozycyjnosc': typeof AuthenticatedDyspozycyjnoscRoute
  '/_authenticated/grafik': typeof AuthenticatedGrafikRoute
  '/_authenticated/ogloszenia': typeof AuthenticatedOgloszeniaRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/pulpit': typeof AuthenticatedPulpitRoute
  '/_authenticated/raporty': typeof AuthenticatedRaportyRoute
  '/_authenticated/statystyki': typeof AuthenticatedStatystykiRoute
  '/_authenticated/urlopy': typeof AuthenticatedUrlopyRoute
  '/_authenticated/zdarzenie': typeof AuthenticatedZdarzenieRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/dziennik': typeof AuthenticatedAdminDziennikRoute
  '/_authenticated/admin/incydenty': typeof AuthenticatedAdminIncydentyRoute
  '/_authenticated/admin/kierowcy': typeof AuthenticatedAdminKierowcyRoute
  '/_authenticated/admin/komunikaty': typeof AuthenticatedAdminKomunikatyRoute
  '/_authenticated/admin/mapa': typeof AuthenticatedAdminMapaRoute
  '/_authenticated/admin/monitor': typeof AuthenticatedAdminMonitorRoute
  '/_authenticated/admin/nieprzydzielone': typeof AuthenticatedAdminNieprzydzieloneRoute
  '/_authenticated/admin/ogloszenia': typeof AuthenticatedAdminOgloszeniaRoute
  '/_authenticated/admin/pojazdy': typeof AuthenticatedAdminPojazdyRoute
  '/_authenticated/admin/raporty': typeof AuthenticatedAdminRaportyRoute
  '/_authenticated/admin/sluzby': typeof AuthenticatedAdminSluzbyRoute
  '/_authenticated/admin/urlopy': typeof AuthenticatedAdminUrlopyRoute
  '/_authenticated/admin/uzytkownicy': typeof AuthenticatedAdminUzytkownicyRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/sluzba/$dutyId/mapa': typeof AuthenticatedSluzbaDutyIdMapaRoute
  '/_authenticated/sluzba/$dutyId/raport': typeof AuthenticatedSluzbaDutyIdRaportRoute
  '/_authenticated/sluzba/$dutyId/rozklad': typeof AuthenticatedSluzbaDutyIdRozkladRoute
  '/_authenticated/sluzba/$dutyId/zdarzenie': typeof AuthenticatedSluzbaDutyIdZdarzenieRoute
  '/api/public/roblox/ack': typeof ApiPublicRobloxAckRoute
  '/api/public/roblox/driver': typeof ApiPublicRobloxDriverRoute
  '/api/public/roblox/duty': typeof ApiPublicRobloxDutyRoute
  '/api/public/roblox/incident': typeof ApiPublicRobloxIncidentRoute
  '/api/public/roblox/pis': typeof ApiPublicRobloxPisRoute
  '/api/public/roblox/position': typeof ApiPublicRobloxPositionRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bootstrap'
    | '/unsubscribe'
    | '/zaproszenie'
    | '/admin'
    | '/dyspozycyjnosc'
    | '/grafik'
    | '/ogloszenia'
    | '/profil'
    | '/pulpit'
    | '/raporty'
    | '/statystyki'
    | '/urlopy'
    | '/zdarzenie'
    | '/email/unsubscribe'
    | '/admin/dashboard'
    | '/admin/dziennik'
    | '/admin/incydenty'
    | '/admin/kierowcy'
    | '/admin/komunikaty'
    | '/admin/mapa'
    | '/admin/monitor'
    | '/admin/nieprzydzielone'
    | '/admin/ogloszenia'
    | '/admin/pojazdy'
    | '/admin/raporty'
    | '/admin/sluzby'
    | '/admin/urlopy'
    | '/admin/uzytkownicy'
    | '/lovable/email/suppression'
    | '/sluzba/$dutyId/mapa'
    | '/sluzba/$dutyId/raport'
    | '/sluzba/$dutyId/rozklad'
    | '/sluzba/$dutyId/zdarzenie'
    | '/api/public/roblox/ack'
    | '/api/public/roblox/driver'
    | '/api/public/roblox/duty'
    | '/api/public/roblox/incident'
    | '/api/public/roblox/pis'
    | '/api/public/roblox/position'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bootstrap'
    | '/unsubscribe'
    | '/zaproszenie'
    | '/admin'
    | '/dyspozycyjnosc'
    | '/grafik'
    | '/ogloszenia'
    | '/profil'
    | '/pulpit'
    | '/raporty'
    | '/statystyki'
    | '/urlopy'
    | '/zdarzenie'
    | '/email/unsubscribe'
    | '/admin/dashboard'
    | '/admin/dziennik'
    | '/admin/incydenty'
    | '/admin/kierowcy'
    | '/admin/komunikaty'
    | '/admin/mapa'
    | '/admin/monitor'
    | '/admin/nieprzydzielone'
    | '/admin/ogloszenia'
    | '/admin/pojazdy'
    | '/admin/raporty'
    | '/admin/sluzby'
    | '/admin/urlopy'
    | '/admin/uzytkownicy'
    | '/lovable/email/suppression'
    | '/sluzba/$dutyId/mapa'
    | '/sluzba/$dutyId/raport'
    | '/sluzba/$dutyId/rozklad'
    | '/sluzba/$dutyId/zdarzenie'
    | '/api/public/roblox/ack'
    | '/api/public/roblox/driver'
    | '/api/public/roblox/duty'
    | '/api/public/roblox/incident'
    | '/api/public/roblox/pis'
    | '/api/public/roblox/position'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/bootstrap'
    | '/unsubscribe'
    | '/zaproszenie'
    | '/_authenticated/admin'
    | '/_authenticated/dyspozycyjnosc'
    | '/_authenticated/grafik'
    | '/_authenticated/ogloszenia'
    | '/_authenticated/profil'
    | '/_authenticated/pulpit'
    | '/_authenticated/raporty'
    | '/_authenticated/statystyki'
    | '/_authenticated/urlopy'
    | '/_authenticated/zdarzenie'
    | '/email/unsubscribe'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/dziennik'
    | '/_authenticated/admin/incydenty'
    | '/_authenticated/admin/kierowcy'
    | '/_authenticated/admin/komunikaty'
    | '/_authenticated/admin/mapa'
    | '/_authenticated/admin/monitor'
    | '/_authenticated/admin/nieprzydzielone'
    | '/_authenticated/admin/ogloszenia'
    | '/_authenticated/admin/pojazdy'
    | '/_authenticated/admin/raporty'
    | '/_authenticated/admin/sluzby'
    | '/_authenticated/admin/urlopy'
    | '/_authenticated/admin/uzytkownicy'
    | '/lovable/email/suppression'
    | '/_authenticated/sluzba/$dutyId/mapa'
    | '/_authenticated/sluzba/$dutyId/raport'
    | '/_authenticated/sluzba/$dutyId/rozklad'
    | '/_authenticated/sluzba/$dutyId/zdarzenie'
    | '/api/public/roblox/ack'
    | '/api/public/roblox/driver'
    | '/api/public/roblox/duty'
    | '/api/public/roblox/incident'
    | '/api/public/roblox/pis'
    | '/api/public/roblox/position'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  BootstrapRoute: typeof BootstrapRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  ZaproszenieRoute: typeof ZaproszenieRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicRobloxAckRoute: typeof ApiPublicRobloxAckRoute
  ApiPublicRobloxDriverRoute: typeof ApiPublicRobloxDriverRoute
  ApiPublicRobloxDutyRoute: typeof ApiPublicRobloxDutyRoute
  ApiPublicRobloxIncidentRoute: typeof ApiPublicRobloxIncidentRoute
  ApiPublicRobloxPisRoute: typeof ApiPublicRobloxPisRoute
  ApiPublicRobloxPositionRoute: typeof ApiPublicRobloxPositionRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zaproszenie': {
      id: '/zaproszenie'
      path: '/zaproszenie'
      fullPath: '/zaproszenie'
      preLoaderRoute: typeof ZaproszenieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bootstrap': {
      id: '/bootstrap'
      path: '/bootstrap'
      fullPath: '/bootstrap'
      preLoaderRoute: typeof BootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/zdarzenie': {
      id: '/_authenticated/zdarzenie'
      path: '/zdarzenie'
      fullPath: '/zdarzenie'
      preLoaderRoute: typeof AuthenticatedZdarzenieRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/urlopy': {
      id: '/_authenticated/urlopy'
      path: '/urlopy'
      fullPath: '/urlopy'
      preLoaderRoute: typeof AuthenticatedUrlopyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/statystyki': {
      id: '/_authenticated/statystyki'
      path: '/statystyki'
      fullPath: '/statystyki'
      preLoaderRoute: typeof AuthenticatedStatystykiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/raporty': {
      id: '/_authenticated/raporty'
      path: '/raporty'
      fullPath: '/raporty'
      preLoaderRoute: typeof AuthenticatedRaportyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pulpit': {
      id: '/_authenticated/pulpit'
      path: '/pulpit'
      fullPath: '/pulpit'
      preLoaderRoute: typeof AuthenticatedPulpitRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ogloszenia': {
      id: '/_authenticated/ogloszenia'
      path: '/ogloszenia'
      fullPath: '/ogloszenia'
      preLoaderRoute: typeof AuthenticatedOgloszeniaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/grafik': {
      id: '/_authenticated/grafik'
      path: '/grafik'
      fullPath: '/grafik'
      preLoaderRoute: typeof AuthenticatedGrafikRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dyspozycyjnosc': {
      id: '/_authenticated/dyspozycyjnosc'
      path: '/dyspozycyjnosc'
      fullPath: '/dyspozycyjnosc'
      preLoaderRoute: typeof AuthenticatedDyspozycyjnoscRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/uzytkownicy': {
      id: '/_authenticated/admin/uzytkownicy'
      path: '/uzytkownicy'
      fullPath: '/admin/uzytkownicy'
      preLoaderRoute: typeof AuthenticatedAdminUzytkownicyRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/urlopy': {
      id: '/_authenticated/admin/urlopy'
      path: '/urlopy'
      fullPath: '/admin/urlopy'
      preLoaderRoute: typeof AuthenticatedAdminUrlopyRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sluzby': {
      id: '/_authenticated/admin/sluzby'
      path: '/sluzby'
      fullPath: '/admin/sluzby'
      preLoaderRoute: typeof AuthenticatedAdminSluzbyRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/raporty': {
      id: '/_authenticated/admin/raporty'
      path: '/raporty'
      fullPath: '/admin/raporty'
      preLoaderRoute: typeof AuthenticatedAdminRaportyRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pojazdy': {
      id: '/_authenticated/admin/pojazdy'
      path: '/pojazdy'
      fullPath: '/admin/pojazdy'
      preLoaderRoute: typeof AuthenticatedAdminPojazdyRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ogloszenia': {
      id: '/_authenticated/admin/ogloszenia'
      path: '/ogloszenia'
      fullPath: '/admin/ogloszenia'
      preLoaderRoute: typeof AuthenticatedAdminOgloszeniaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/nieprzydzielone': {
      id: '/_authenticated/admin/nieprzydzielone'
      path: '/nieprzydzielone'
      fullPath: '/admin/nieprzydzielone'
      preLoaderRoute: typeof AuthenticatedAdminNieprzydzieloneRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/monitor': {
      id: '/_authenticated/admin/monitor'
      path: '/monitor'
      fullPath: '/admin/monitor'
      preLoaderRoute: typeof AuthenticatedAdminMonitorRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/mapa': {
      id: '/_authenticated/admin/mapa'
      path: '/mapa'
      fullPath: '/admin/mapa'
      preLoaderRoute: typeof AuthenticatedAdminMapaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/komunikaty': {
      id: '/_authenticated/admin/komunikaty'
      path: '/komunikaty'
      fullPath: '/admin/komunikaty'
      preLoaderRoute: typeof AuthenticatedAdminKomunikatyRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/kierowcy': {
      id: '/_authenticated/admin/kierowcy'
      path: '/kierowcy'
      fullPath: '/admin/kierowcy'
      preLoaderRoute: typeof AuthenticatedAdminKierowcyRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/incydenty': {
      id: '/_authenticated/admin/incydenty'
      path: '/incydenty'
      fullPath: '/admin/incydenty'
      preLoaderRoute: typeof AuthenticatedAdminIncydentyRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dziennik': {
      id: '/_authenticated/admin/dziennik'
      path: '/dziennik'
      fullPath: '/admin/dziennik'
      preLoaderRoute: typeof AuthenticatedAdminDziennikRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/roblox/position': {
      id: '/api/public/roblox/position'
      path: '/api/public/roblox/position'
      fullPath: '/api/public/roblox/position'
      preLoaderRoute: typeof ApiPublicRobloxPositionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/roblox/pis': {
      id: '/api/public/roblox/pis'
      path: '/api/public/roblox/pis'
      fullPath: '/api/public/roblox/pis'
      preLoaderRoute: typeof ApiPublicRobloxPisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/roblox/incident': {
      id: '/api/public/roblox/incident'
      path: '/api/public/roblox/incident'
      fullPath: '/api/public/roblox/incident'
      preLoaderRoute: typeof ApiPublicRobloxIncidentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/roblox/duty': {
      id: '/api/public/roblox/duty'
      path: '/api/public/roblox/duty'
      fullPath: '/api/public/roblox/duty'
      preLoaderRoute: typeof ApiPublicRobloxDutyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/roblox/driver': {
      id: '/api/public/roblox/driver'
      path: '/api/public/roblox/driver'
      fullPath: '/api/public/roblox/driver'
      preLoaderRoute: typeof ApiPublicRobloxDriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/roblox/ack': {
      id: '/api/public/roblox/ack'
      path: '/api/public/roblox/ack'
      fullPath: '/api/public/roblox/ack'
      preLoaderRoute: typeof ApiPublicRobloxAckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sluzba/$dutyId/zdarzenie': {
      id: '/_authenticated/sluzba/$dutyId/zdarzenie'
      path: '/sluzba/$dutyId/zdarzenie'
      fullPath: '/sluzba/$dutyId/zdarzenie'
      preLoaderRoute: typeof AuthenticatedSluzbaDutyIdZdarzenieRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sluzba/$dutyId/rozklad': {
      id: '/_authenticated/sluzba/$dutyId/rozklad'
      path: '/sluzba/$dutyId/rozklad'
      fullPath: '/sluzba/$dutyId/rozklad'
      preLoaderRoute: typeof AuthenticatedSluzbaDutyIdRozkladRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sluzba/$dutyId/raport': {
      id: '/_authenticated/sluzba/$dutyId/raport'
      path: '/sluzba/$dutyId/raport'
      fullPath: '/sluzba/$dutyId/raport'
      preLoaderRoute: typeof AuthenticatedSluzbaDutyIdRaportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sluzba/$dutyId/mapa': {
      id: '/_authenticated/sluzba/$dutyId/mapa'
      path: '/sluzba/$dutyId/mapa'
      fullPath: '/sluzba/$dutyId/mapa'
      preLoaderRoute: typeof AuthenticatedSluzbaDutyIdMapaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminDziennikRoute: typeof AuthenticatedAdminDziennikRoute
  AuthenticatedAdminIncydentyRoute: typeof AuthenticatedAdminIncydentyRoute
  AuthenticatedAdminKierowcyRoute: typeof AuthenticatedAdminKierowcyRoute
  AuthenticatedAdminKomunikatyRoute: typeof AuthenticatedAdminKomunikatyRoute
  AuthenticatedAdminMapaRoute: typeof AuthenticatedAdminMapaRoute
  AuthenticatedAdminMonitorRoute: typeof AuthenticatedAdminMonitorRoute
  AuthenticatedAdminNieprzydzieloneRoute: typeof AuthenticatedAdminNieprzydzieloneRoute
  AuthenticatedAdminOgloszeniaRoute: typeof AuthenticatedAdminOgloszeniaRoute
  AuthenticatedAdminPojazdyRoute: typeof AuthenticatedAdminPojazdyRoute
  AuthenticatedAdminRaportyRoute: typeof AuthenticatedAdminRaportyRoute
  AuthenticatedAdminSluzbyRoute: typeof AuthenticatedAdminSluzbyRoute
  AuthenticatedAdminUrlopyRoute: typeof AuthenticatedAdminUrlopyRoute
  AuthenticatedAdminUzytkownicyRoute: typeof AuthenticatedAdminUzytkownicyRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminDziennikRoute: AuthenticatedAdminDziennikRoute,
  AuthenticatedAdminIncydentyRoute: AuthenticatedAdminIncydentyRoute,
  AuthenticatedAdminKierowcyRoute: AuthenticatedAdminKierowcyRoute,
  AuthenticatedAdminKomunikatyRoute: AuthenticatedAdminKomunikatyRoute,
  AuthenticatedAdminMapaRoute: AuthenticatedAdminMapaRoute,
  AuthenticatedAdminMonitorRoute: AuthenticatedAdminMonitorRoute,
  AuthenticatedAdminNieprzydzieloneRoute:
    AuthenticatedAdminNieprzydzieloneRoute,
  AuthenticatedAdminOgloszeniaRoute: AuthenticatedAdminOgloszeniaRoute,
  AuthenticatedAdminPojazdyRoute: AuthenticatedAdminPojazdyRoute,
  AuthenticatedAdminRaportyRoute: AuthenticatedAdminRaportyRoute,
  AuthenticatedAdminSluzbyRoute: AuthenticatedAdminSluzbyRoute,
  AuthenticatedAdminUrlopyRoute: AuthenticatedAdminUrlopyRoute,
  AuthenticatedAdminUzytkownicyRoute: AuthenticatedAdminUzytkownicyRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDyspozycyjnoscRoute: typeof AuthenticatedDyspozycyjnoscRoute
  AuthenticatedGrafikRoute: typeof AuthenticatedGrafikRoute
  AuthenticatedOgloszeniaRoute: typeof AuthenticatedOgloszeniaRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedPulpitRoute: typeof AuthenticatedPulpitRoute
  AuthenticatedRaportyRoute: typeof AuthenticatedRaportyRoute
  AuthenticatedStatystykiRoute: typeof AuthenticatedStatystykiRoute
  AuthenticatedUrlopyRoute: typeof AuthenticatedUrlopyRoute
  AuthenticatedZdarzenieRoute: typeof AuthenticatedZdarzenieRoute
  AuthenticatedSluzbaDutyIdMapaRoute: typeof AuthenticatedSluzbaDutyIdMapaRoute
  AuthenticatedSluzbaDutyIdRaportRoute: typeof AuthenticatedSluzbaDutyIdRaportRoute
  AuthenticatedSluzbaDutyIdRozkladRoute: typeof AuthenticatedSluzbaDutyIdRozkladRoute
  AuthenticatedSluzbaDutyIdZdarzenieRoute: typeof AuthenticatedSluzbaDutyIdZdarzenieRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDyspozycyjnoscRoute: AuthenticatedDyspozycyjnoscRoute,
  AuthenticatedGrafikRoute: AuthenticatedGrafikRoute,
  AuthenticatedOgloszeniaRoute: AuthenticatedOgloszeniaRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedPulpitRoute: AuthenticatedPulpitRoute,
  AuthenticatedRaportyRoute: AuthenticatedRaportyRoute,
  AuthenticatedStatystykiRoute: AuthenticatedStatystykiRoute,
  AuthenticatedUrlopyRoute: AuthenticatedUrlopyRoute,
  AuthenticatedZdarzenieRoute: AuthenticatedZdarzenieRoute,
  AuthenticatedSluzbaDutyIdMapaRoute: AuthenticatedSluzbaDutyIdMapaRoute,
  AuthenticatedSluzbaDutyIdRaportRoute: AuthenticatedSluzbaDutyIdRaportRoute,
  AuthenticatedSluzbaDutyIdRozkladRoute: AuthenticatedSluzbaDutyIdRozkladRoute,
  AuthenticatedSluzbaDutyIdZdarzenieRoute:
    AuthenticatedSluzbaDutyIdZdarzenieRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  BootstrapRoute: BootstrapRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  ZaproszenieRoute: ZaproszenieRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicRobloxAckRoute: ApiPublicRobloxAckRoute,
  ApiPublicRobloxDriverRoute: ApiPublicRobloxDriverRoute,
  ApiPublicRobloxDutyRoute: ApiPublicRobloxDutyRoute,
  ApiPublicRobloxIncidentRoute: ApiPublicRobloxIncidentRoute,
  ApiPublicRobloxPisRoute: ApiPublicRobloxPisRoute,
  ApiPublicRobloxPositionRoute: ApiPublicRobloxPositionRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
